/**
 * Inlines the vendored Neon agent skills into `src/generated.ts`.
 *
 * The coding agent runs as a Neon Function: esbuild bundles it and ships a
 * single file, so it has no filesystem to read `.agents/skills/` from at
 * runtime. Generating a TypeScript module keeps the markdown in the bundle
 * while `.agents/skills/` stays the single source of truth (refresh it with
 * the root `skills:sync` script, then re-run this).
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { parse } from "yaml";

/** Skills exposed to the coding agent, in the order they appear in its catalog. */
const SKILL_NAMES = [
  "neon",
  "neon-postgres",
  "neon-functions",
  "neon-object-storage",
  "neon-ai-gateway",
] as const;

const ROOT = resolve(import.meta.dirname, "../../..");
const SKILLS_DIR = join(ROOT, ".agents/skills");
const OUT = resolve(import.meta.dirname, "../src/generated.ts");

interface Frontmatter {
  name: string;
  description: string;
}

function assertFrontmatter(value: unknown, file: string): asserts value is Frontmatter {
  if (typeof value !== "object" || value === null) {
    throw new Error(`${file}: frontmatter is not a mapping`);
  }
  if (!("name" in value) || typeof value.name !== "string") {
    throw new Error(`${file}: frontmatter is missing a string \`name\``);
  }
  if (!("description" in value) || typeof value.description !== "string") {
    throw new Error(`${file}: frontmatter is missing a string \`description\``);
  }
}

/** Split `---\n…\n---\n<body>` into its parsed frontmatter and body. */
function splitFrontmatter(source: string, file: string): { meta: Frontmatter; body: string } {
  if (!source.startsWith("---\n")) {
    throw new Error(`${file}: expected YAML frontmatter`);
  }
  const end = source.indexOf("\n---", 3);
  if (end === -1) {
    throw new Error(`${file}: unterminated YAML frontmatter`);
  }
  const meta: unknown = parse(source.slice(4, end + 1));
  assertFrontmatter(meta, file);
  return { meta, body: source.slice(source.indexOf("\n", end + 1) + 1).trim() };
}

/** Every markdown file under a skill directory, relative to that directory. */
async function markdownFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { recursive: true, withFileTypes: true });
  return entries
    .filter((e) => e.isFile() && e.name.endsWith(".md"))
    .map((e) => relative(dir, join(e.parentPath, e.name)))
    .sort();
}

const skills: string[] = [];

for (const name of SKILL_NAMES) {
  const dir = join(SKILLS_DIR, name);
  const paths = await markdownFiles(dir);
  const skillPath = paths.find((p) => p === "SKILL.md");
  if (skillPath === undefined) {
    throw new Error(`${name}: no SKILL.md — run \`bun run skills:sync\` from the repo root`);
  }

  const { meta, body } = splitFrontmatter(await readFile(join(dir, skillPath), "utf8"), name);
  const files: string[] = [`    "SKILL.md": ${JSON.stringify(body)},`];

  for (const path of paths) {
    if (path === "SKILL.md") continue;
    const content = await readFile(join(dir, path), "utf8");
    files.push(`    ${JSON.stringify(path)}: ${JSON.stringify(content.trim())},`);
  }

  skills.push(
    [
      `  ${JSON.stringify(name)}: {`,
      `    name: ${JSON.stringify(meta.name)},`,
      `    description: ${JSON.stringify(meta.description.trim())},`,
      `    files: {`,
      ...files,
      `    },`,
      `  },`,
    ].join("\n"),
  );
}

const source = `// GENERATED by packages/skills/scripts/generate.ts — do not edit.
// Source of truth: .agents/skills/. Refresh with \`bun run skills:sync\`
// from the repo root, then \`bun run --filter @vibe/skills generate\`.
import type { Skill } from "./types";

export const GENERATED_SKILLS: Record<string, Skill> = {
${skills.join("\n")}
};
`;

await writeFile(OUT, source);
console.log(`wrote ${relative(ROOT, OUT)} (${SKILL_NAMES.length} skills)`);
